// <auto-generated />
namespace Netzalist.LeadManager.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class lastchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201312041651357_lastchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
