// <auto-generated />
namespace Netzalist.LeadManager.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddExplicitForeignKeyToCompany2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExplicitForeignKeyToCompany2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311052037384_AddExplicitForeignKeyToCompany2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
