// <auto-generated />
namespace Netzalist.LeadManager.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DBTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201310131453245_DBTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
